/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Servicios.ServicioCuenta;
import controlador.Sesiones;
import controlador.Utilidades;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import vista.Utilidades.Validacion;

/**
 *
 * @author Steven Y
 */
public class frm_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form frm_Inicio
     */
    private ServicioCuenta sCuenta = new ServicioCuenta();
    private String ruta="";
    private  String foto= "";
    public frm_Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        this.panelFoto.setImagen(new ImageIcon (getClass().getResource("/vista/imagenes/Live Messenger blue.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnSalir = new org.edisoncor.gui.button.ButtonAction();
        btnIniciar = new org.edisoncor.gui.button.ButtonAction();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImaFondo = new org.edisoncor.gui.panel.PanelImage();
        panelFoto = new vista.componentes.PanelImagen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  INGRESO AL SISTEMA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 220, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLAVE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 30));

        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, 30));

        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClaveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveKeyTyped(evt);
            }
        });
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, 30));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.setColorDeSombra(new java.awt.Color(255, 255, 255));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 80, -1));

        btnIniciar.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("INICIAR");
        btnIniciar.setColorDeSombra(new java.awt.Color(0, 0, 51));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 80, -1));
        getContentPane().add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        panelImaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/fondoventana1.jpeg"))); // NOI18N
        panelImaFondo.setLayout(null);
        panelImaFondo.add(panelFoto);
        panelFoto.setBounds(260, 50, 140, 140);

        getContentPane().add(panelImaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        this.irPrincipal();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        Validacion.ValidaLetrasNumerosEspacio(evt);
        Validacion.cambiarMayusculas(evt);
        Validacion.validarlogin(evt);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyTyped
        Validacion.ValidaLetrasNumerosEspacio(evt);
        Validacion.cambiarMayusculas(evt);
        Validacion.validarlogin(evt);
        
    }//GEN-LAST:event_txtClaveKeyTyped

    private void txtClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            this.irPrincipal();
        }
    }//GEN-LAST:event_txtClaveKeyPressed

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        this.sCuenta.fijarInstancia(this.sCuenta.traerUsuario(this.txtUsuario.getText()));
        if(this.sCuenta.getCuenta().getUsu()!= null){
            
        System.out.println(this.sCuenta.getCuenta().getUsu().getTip_usu());
            this.ruta = Utilidades.getRutaFotos() + File.separatorChar + this.sCuenta.getCuenta().getUsu().getFoto();
            this.panelFoto.setImagen(new ImageIcon(this.ruta));
            this.panelFoto.updateUI();
        }else{
            JOptionPane.showMessageDialog(this, "USUARIO NO SE ENCUENTRA REGISTRADO!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
            this.errorIniciar();
        }
        
    }//GEN-LAST:event_txtUsuarioFocusLost
    private void errorIniciar(){
        this.txtUsuario.setText("");
        this.txtClave.setText("");
        this.txtUsuario.requestFocus();
        this.panelFoto.setImagen(new ImageIcon (getClass().getResource("/vista/imagenes/Live Messenger blue.png")));
        this.panelFoto.updateUI();
    }
    private void irPrincipal()
    {
        String clave="";
        for(int i=0; i<txtClave.getPassword().length;i++)
        {
            clave+= txtClave.getPassword()[i];//
        }
        if(Validacion.requerido(txtUsuario,txtUsuario.getText())== true && Validacion.requerido(txtClave, clave)== true){
            ServicioCuenta sc = new ServicioCuenta();
            Sesiones.setCuenta(sc.iniciarSecion(txtUsuario.getText(), clave));
            if(Sesiones.getCuenta()!=null && Sesiones.getCuenta().getUsu()!=null)
            {
                this.dispose();
                new frmPrincipal().setVisible(true);
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"No esta registrado en el sistema o su usuario y clave son incorrectas","Error", JOptionPane.ERROR_MESSAGE);
                this.errorIniciar();
            }
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction btnIniciar;
    private org.edisoncor.gui.button.ButtonAction btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private vista.componentes.PanelImagen panelFoto;
    private org.edisoncor.gui.panel.PanelImage panelImaFondo;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
