package vista;
import controlador.Servicios.ServicioCliente;
import controlador.Servicios.ServicioCuenta;
import controlador.Servicios.ServicioPersona;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import vista.Utilidades.LimitarCaracter;
import vista.Utilidades.Validacion;
import vista.Utilidades.ValidacionIdentidad;
import vista.modeloTabla.ModeloTablaCliente;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
    
/**
 *
 * @author Steven Y
 */
public class frm_Cliente extends javax.swing.JDialog {

    /**
     * Creates new form frm_Cliente
     */
      private ServicioPersona sp = new ServicioPersona();
      private ServicioCuenta sc = new ServicioCuenta();
      private ServicioCliente scli = new ServicioCliente();
      private ModeloTablaCliente modeloC = new ModeloTablaCliente();
      
      
    public frm_Cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.cargarTabla();
        this.Limitar();
        this.setSize(625, 337);
        this.Limitar();
        tblClientes.getTableHeader().setBackground(Color.blue);
        tblClientes.getTableHeader().setForeground(Color.white);
        tblClientes.getTableHeader().setFont(new Font("", Font.BOLD, 12));
    }      
    
    public void Limitar(){
        this.txtCedula.setDocument(new LimitarCaracter(txtCedula, 10));
        this.txtTelefono.setDocument(new LimitarCaracter(txtTelefono, 10));
    }
    private void limpiarCampos()
    {
        this.scli.nuevaInstancia();
        this.sp.nuevaInstancia();
        this.txtCedula.setText("");
        this.txtApellidos.setText("");
        this.txtNombres.setText("");
        this.txtTelefono.setText("");
        this.txtCedula.setEditable(true);
        this.txtEmail.setText("");
        this.txtDireccionCliente.setText("");
 
    }
    
    private void irListar() {
    }
    
    private void cargarTabla()
    {
       //this.modeloC.setLista(this.scli.listar()); //Alimentamos la lista 
        // this.modeloCli.setLista(this.scli.listaPersonasClientes(""));
        this.modeloC.setLista(this.scli.listar());
        this.tblClientes.setModel(this.modeloC);
        this.tblClientes.updateUI();
    }
    public void verificarCedula() {
        if (!txtCedula.getText().isEmpty()) {
            if (ValidacionIdentidad.validarCedula(txtCedula.getText()) == false) {
                JOptionPane.showMessageDialog(this, "La cedula es incorrecta!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } 
        
     private void cargarObjeto() {
        //Todos los objetos 
        this.scli.getCliente().setCed_per(txtCedula.getText());
        this.scli.getCliente().setApe_per(txtApellidos.getText());
        this.scli.getCliente().setNom_per(txtNombres.getText());
        this.scli.getCliente().setTel_per(txtTelefono.getText());
        this.scli.getCliente().setEma_per(txtEmail.getText());
        this.scli.getCliente().setDir_per(txtDireccionCliente.getText());
        this.scli.getCliente().setEst_per("ACTIVO");
        if (rdbMasculino.isSelected()) {
            this.scli.getCliente().setSex_per("M");
        } else {
            if (rdbFemenino.isSelected()) {
                this.scli.getCliente().setSex_per("F");
            }
        }
    }
  private  void cargarVista()
    {
       this.txtCedula.setText(this.scli.getCliente().getCed_per());
       this.txtApellidos.setText(this.scli.getCliente().getApe_per());
        this.txtNombres.setText(this.scli.getCliente().getNom_per());
        this.txtTelefono.setText(this.scli.getCliente().getTel_per());
        this.txtEmail.setText(this.scli.getCliente().getEma_per());
        this.txtDireccionCliente.setText(this.scli.getCliente().getDir_per());
        this.scli.getCliente().setEst_per("ACTIVO");
        
        if(this.scli.getCliente().getSex_per().equals("M")){
            this.rdbMasculino.setSelected(true);
        }
         if(this.scli.getCliente().getSex_per().equals("F"))
        {
         this.rdbFemenino.setSelected(true);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexoCliente = new javax.swing.ButtonGroup();
        panelFondo = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        panelReflect1 = new org.edisoncor.gui.panel.PanelReflect();
        jLabel2 = new javax.swing.JLabel();
        cbxBuscarClientes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtBuscarCliente = new javax.swing.JTextField();
        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelReflect2 = new org.edisoncor.gui.panel.PanelReflect();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDireccionCliente = new javax.swing.JTextArea();
        rdbMasculino = new javax.swing.JRadioButton();
        rdbFemenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(610, 400));

        panelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/F9PVwxM.jpg"))); // NOI18N
        panelFondo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMNISTRAR CLIENTES");
        panelFondo.add(jLabel1);
        jLabel1.setBounds(150, 10, 302, 45);

        panelReflect1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSQUEDA DE CLIENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelReflect1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSCAR POR:");
        panelReflect1.add(jLabel2);
        jLabel2.setBounds(10, 20, 90, 25);

        cbxBuscarClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar Opcion", "Apellidos", "Cedula" }));
        cbxBuscarClientes.setName(""); // NOI18N
        cbxBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBuscarClientesActionPerformed(evt);
            }
        });
        panelReflect1.add(cbxBuscarClientes);
        cbxBuscarClientes.setBounds(100, 20, 130, 20);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        panelReflect1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 550, 110);

        txtBuscarCliente.setEditable(false);
        txtBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarClienteMouseClicked(evt);
            }
        });
        txtBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarClienteActionPerformed(evt);
            }
        });
        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyTyped(evt);
            }
        });
        panelReflect1.add(txtBuscarCliente);
        txtBuscarCliente.setBounds(240, 10, 190, 30);

        panelFondo.add(panelReflect1);
        panelReflect1.setBounds(20, 50, 580, 190);

        panelRectTranslucido1.setLayout(null);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/new.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setBorder(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelRectTranslucido1.add(btnNuevo);
        btnNuevo.setBounds(220, 10, 101, 34);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/producto.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(null);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelRectTranslucido1.add(btnModificar);
        btnModificar.setBounds(340, 10, 101, 34);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/cancel.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelRectTranslucido1.add(btnSalir);
        btnSalir.setBounds(450, 10, 101, 34);

        panelFondo.add(panelRectTranslucido1);
        panelRectTranslucido1.setBounds(20, 240, 570, 58);

        panelReflect2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelReflect2.setLayout(null);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/save.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelReflect2.add(btnGuardar);
        btnGuardar.setBounds(410, 150, 110, 40);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/cancel.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelReflect2.add(btnCancelar);
        btnCancelar.setBounds(410, 200, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEXO:");
        panelReflect2.add(jLabel3);
        jLabel3.setBounds(350, 30, 70, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CÉDULA:");
        panelReflect2.add(jLabel4);
        jLabel4.setBounds(10, 30, 60, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDOS:");
        panelReflect2.add(jLabel5);
        jLabel5.setBounds(10, 70, 80, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRES:");
        panelReflect2.add(jLabel6);
        jLabel6.setBounds(10, 110, 70, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TELÉFONO:");
        panelReflect2.add(jLabel7);
        jLabel7.setBounds(10, 140, 70, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EMAIL:");
        panelReflect2.add(jLabel8);
        jLabel8.setBounds(10, 180, 70, 25);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panelReflect2.add(txtEmail);
        txtEmail.setBounds(90, 180, 240, 30);

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        panelReflect2.add(txtCedula);
        txtCedula.setBounds(90, 20, 100, 30);

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        panelReflect2.add(txtApellidos);
        txtApellidos.setBounds(90, 60, 240, 30);

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        panelReflect2.add(txtNombres);
        txtNombres.setBounds(90, 100, 240, 30);

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        panelReflect2.add(txtTelefono);
        txtTelefono.setBounds(90, 140, 160, 30);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDireccionCliente.setColumns(20);
        txtDireccionCliente.setRows(5);
        txtDireccionCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionClienteKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(txtDireccionCliente);

        panelReflect2.add(jScrollPane6);
        jScrollPane6.setBounds(90, 220, 240, 50);

        grupoSexoCliente.add(rdbMasculino);
        rdbMasculino.setText("MASCULINO");
        rdbMasculino.setOpaque(false);
        panelReflect2.add(rdbMasculino);
        rdbMasculino.setBounds(410, 30, 90, 23);

        grupoSexoCliente.add(rdbFemenino);
        rdbFemenino.setText("FEMENINO");
        rdbFemenino.setOpaque(false);
        panelReflect2.add(rdbFemenino);
        rdbFemenino.setBounds(410, 60, 90, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DIRECCIÓN:");
        panelReflect2.add(jLabel9);
        jLabel9.setBounds(10, 220, 70, 25);

        panelFondo.add(panelReflect2);
        panelReflect2.setBounds(20, 310, 580, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(626, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:ç
        this.irNuevo();
        this.setSize(625, 650);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
         if (Validacion.requerido(txtCedula, txtCedula.getText()) == true
                && Validacion.requerido(txtApellidos, txtApellidos.getText()) == true
                && Validacion.requerido(txtNombres, txtNombres.getText()) == true
                && Validacion.requerido(txtTelefono, txtTelefono.getText()) == true
                && Validacion.requerido(txtEmail, txtEmail.getText()) == true
                && Validacion.requerido(txtDireccionCliente, txtDireccionCliente.getText()) == true) {//valida q los campos no esten vacios
            if (Validacion.validarCedula(txtCedula.getText()) == true) {//si la cedula ingresada es correcta
                this.cargarObjeto();//cargamos los datos
                if (this.scli.getCliente().getId_persona() == null) {//verificamos si ya tiene id
                    if (new ServicioPersona().obtenerPersonaCedula(txtCedula.getText()) == null){//si la cedula es unica
                        if (rdbMasculino.isSelected()) {
                            this.scli.getCliente().setSex_per("M");
                                 } else {
                                  if (rdbFemenino.isSelected()) {
                                     this.scli.getCliente().setSex_per("F");
                             }
                        }
                        if (this.scli.guardar()== true){//guardamos el objeto5
                            JOptionPane.showMessageDialog(this, "SE HA REGISTRADO CORRECTAMENTE", "OK", JOptionPane.INFORMATION_MESSAGE);
                            this.limpiarCampos();
                            this.irListar();
                            this.cargarTabla();
                            this.setSize(625, 337);
                        }else{
                            JOptionPane.showMessageDialog(this, "NO SE PUEDE REGISTRAR!!", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "YA EXISTE CEDULA!!", "ERROR", JOptionPane.ERROR_MESSAGE);
                        this.limpiarCampos();
                    }
                } else {//editar
                    if (this.scli.modificar() == true) {
                        JOptionPane.showMessageDialog(this, "SE HA MODIFICADO CORRECTAMENTE", "OK", JOptionPane.INFORMATION_MESSAGE);
                        this.limpiarCampos();
                        this.irListar();
                        this.cargarTabla();
                        this.setSize(625, 337);
                    } else {
                        JOptionPane.showMessageDialog(this, "No se ha podido modificado!!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "La cedula es incorrecta!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        int fila = tblClientes.getSelectedRow();
        if(fila>=0){
            this.scli.fijarInstancia(this.modeloC.getLista().get(fila)); //se fija la fila
            this.tblClientes.clearSelection(); //quitar seleccion de la tabla
            this.cargarVista();
            this.txtCedula.setEditable(false);//nose va a ppoder editar
            this.setSize(625, 650);
        }   
        else
        {
            JOptionPane.showMessageDialog(this, "Escoja un registro de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setSize(625, 337);
        this.irListar();
        this.limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesKeyReleased
       this.setSize(625, 337);
    }//GEN-LAST:event_tblClientesKeyReleased

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        this.setSize(625, 337);
    }//GEN-LAST:event_tblClientesMouseClicked

    private void txtBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarClienteMouseClicked
        // habilitar el txt
        if (cbxBuscarClientes.getSelectedIndex() == 2) {
            txtBuscarCliente.setEnabled(true);
            txtBuscarCliente.setText("");
        }
    }//GEN-LAST:event_txtBuscarClienteMouseClicked

    private void txtBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarClienteActionPerformed
        // habilitar el txt
        if (cbxBuscarClientes.getSelectedIndex() == 2) {
            txtBuscarCliente.setEnabled(true);
            txtBuscarCliente.setText("");
            txtBuscarCliente.requestFocus();
        }
    }//GEN-LAST:event_txtBuscarClienteActionPerformed

    private void txtBuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyReleased
       Validacion.validarMayusculas(evt, txtBuscarCliente);
        
        if(cbxBuscarClientes.getSelectedIndex() == 1){
            this.modeloC.setLista(this.scli.buscarTodosClientes(this.txtBuscarCliente.getText()));
           // this.modeloAlumno.setLista(this.sAlumno.buscarTodosAlumnos(this.txtBuscarAlumno.getText()));
        }else{
            if(cbxBuscarClientes.getSelectedIndex() == 2){
               // SimpleDateFormat formato = new SimpleDateFormat("yy-MM-ddd");
               this.modeloC.setLista(this.scli.buscarClienteporCedula(this.txtBuscarCliente.getText()));
            }
        }

        this.tblClientes.setModel(this.modeloC);
        this.tblClientes.updateUI();
    }//GEN-LAST:event_txtBuscarClienteKeyReleased

    private void txtBuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyTyped
        // verifica el tipo de caracter a recibir
        if (cbxBuscarClientes.getSelectedIndex() == 1) {
            Validacion.ValidarLetras(evt);
        } else {
            if (cbxBuscarClientes.getSelectedIndex() > 1) {
                Validacion.validarNumeros(evt);
            }
        }
    }//GEN-LAST:event_txtBuscarClienteKeyTyped

    private void cbxBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBuscarClientesActionPerformed
       // seleccionar el criterio de busqueda
        if (cbxBuscarClientes.getSelectedIndex() == 0) {
            txtBuscarCliente.setEditable(false);           
            txtBuscarCliente.setEnabled(false);
            txtBuscarCliente.setText("");
        } else {
            txtBuscarCliente.setEnabled(true);
            txtBuscarCliente.setEditable(true);
            txtBuscarCliente.requestFocus();
            txtBuscarCliente.setText("");
            if (cbxBuscarClientes.getSelectedIndex() == 2) {
                txtBuscarCliente.setEnabled(false);
               // txtBuscarPedido.setText("YYY-MM-DD");
            }
        }
    }//GEN-LAST:event_cbxBuscarClientesActionPerformed

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        Validacion.ValidarLetrasEspacio(evt);
        Validacion.cambiarMayusculas(evt);
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        this.verificarCedula();
    }//GEN-LAST:event_txtCedulaFocusLost

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        Validacion.ValidarNumeros(evt);
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
         Validacion.ValidarLetrasEspacio(evt);
        Validacion.cambiarMayusculas(evt);
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        Validacion.ValidarNumeros(evt);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtDireccionClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionClienteKeyTyped
        Validacion.cambiarMayusculas(evt);
    }//GEN-LAST:event_txtDireccionClienteKeyTyped

    public void irNuevo() {
        this.limpiarCampos();
        this.rdbMasculino.setSelected(true);
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_Cliente dialog = new frm_Cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbxBuscarClientes;
    private javax.swing.ButtonGroup grupoSexoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private org.edisoncor.gui.panel.PanelImage panelFondo;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private org.edisoncor.gui.panel.PanelReflect panelReflect1;
    private org.edisoncor.gui.panel.PanelReflect panelReflect2;
    private javax.swing.JRadioButton rdbFemenino;
    private javax.swing.JRadioButton rdbMasculino;
    private javax.swing.JTable tblClientes;
    public static javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscarCliente;
    public static javax.swing.JTextField txtCedula;
    private javax.swing.JTextArea txtDireccionCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}