/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Reportes.ReporteFactura;
import controlador.Servicios.ServicioFactura;
import controlador.Sesiones;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Cliente;
import vista.Utilidades.Validacion;
import vista.modeloTabla.ModeloTablaFacturas;

/**
 *
 * @author Steven Y
 */
public class Frm_Facturas extends javax.swing.JDialog {

    /**
     * Creates new form Frm_Abono
     */
    private ModeloTablaFacturas modeloTablaFacturas = new ModeloTablaFacturas();
    private ServicioFactura sFactura = new ServicioFactura();
    
    public Frm_Facturas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.CargarTabla();
        this.modeloTablaFacturas.tablaModel(tblFacturas);
        this.btnImprimir.setEnabled(false);
        this.btnCancelar.setEnabled(false);
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        jLabel2 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cbxCriterio = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setTitle("REIMPRESION DE FACTURAS");

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/F9PVwxM.jpg"))); // NOI18N
        panelImage1.setLayout(null);

        labelMetric1.setBackground(new java.awt.Color(255, 255, 255));
        labelMetric1.setText("FACTURAS EFECTUADAS");
        labelMetric1.setColorDeSombra(new java.awt.Color(0, 0, 51));
        labelMetric1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        panelImage1.add(labelMetric1);
        labelMetric1.setBounds(170, 10, 330, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSQUEDA:");
        panelImage1.add(jLabel2);
        jLabel2.setBounds(30, 60, 80, 20);

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        panelImage1.add(txtBusqueda);
        txtBusqueda.setBounds(280, 60, 190, 25);

        cbxCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CRITERIO", "NUM. FACTURA", "APELLIDOS", "" }));
        cbxCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCriterioActionPerformed(evt);
            }
        });
        panelImage1.add(cbxCriterio);
        cbxCriterio.setBounds(120, 60, 150, 25);

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFacturas);

        panelImage1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 600, 200);

        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        panelImage1.add(btnImprimir);
        btnImprimir.setBounds(340, 320, 90, 23);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelImage1.add(btnCancelar);
        btnCancelar.setBounds(440, 320, 100, 23);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelImage1.add(btnSalir);
        btnSalir.setBounds(550, 320, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("REIMPRESIÓN DE FACTURAS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacturasMouseClicked
        int fila = this.tblFacturas.getSelectedRow();
        if (fila >= 0) {
            this.sFactura.fijarInstancia(this.modeloTablaFacturas.getLista().get(fila));
            this.btnImprimir.setEnabled(true);
            this.btnCancelar.setEnabled(true);
        } else {
            this.btnImprimir.setEnabled(false);
            this.btnCancelar.setEnabled(false);
        }
    }//GEN-LAST:event_tblFacturasMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.tblFacturas.clearSelection();
       this.sFactura.nuevaInstancia();
       this.btnImprimir.setEnabled(false);
       this.btnCancelar.setEnabled(false);
       this.cbxCriterio.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String usuario = (Sesiones.getCuenta().getUsu().getApe_per() + " " + Sesiones.getCuenta().getUsu().getNom_per());
        ReporteFactura.reporteFactura(this.sFactura.getFactura(), usuario);
        this.tblFacturas.clearSelection();
        this.btnImprimir.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.cbxCriterio.setSelectedIndex(0);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void cbxCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCriterioActionPerformed
        if (cbxCriterio.getSelectedIndex() == 0) {
            // txtBuscarCuenta.setEditable(false);
            txtBusqueda.setEnabled(false);
            txtBusqueda.setText("");
        } else {
            txtBusqueda.setEnabled(true);
            //txtBuscarCuenta.setEditable(true);
            txtBusqueda.requestFocus();
            txtBusqueda.setText("");

            if (cbxCriterio.getSelectedIndex() == 2) {
                txtBusqueda.setEnabled(true);
                txtBusqueda.requestFocus();
                txtBusqueda.setText("");
            }
        }
    }//GEN-LAST:event_cbxCriterioActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
         // habilitar el txt
        if (cbxCriterio.getSelectedIndex() == 2) {
            txtBusqueda.setEnabled(true);
            txtBusqueda.setText("");
            txtBusqueda.requestFocus();
        }
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        Validacion.validarMayusculas(evt, txtBusqueda);
        //Buscar los pedidos
        if (cbxCriterio.getSelectedIndex() == 1) {
           
            this.modeloTablaFacturas.setLista(this.sFactura.buscarxNumFactura(this.txtBusqueda.getText()));
        } else{ if (cbxCriterio.getSelectedIndex() == 2) {
          
            this.modeloTablaFacturas.setLista(this.sFactura.buscarporCedula(this.txtBusqueda.getText()));
        } 
        }
        this.tblFacturas.setModel(this.modeloTablaFacturas);
        this.tblFacturas.updateUI();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
             if (cbxCriterio.getSelectedIndex() == 1) {
            Validacion.validarNumeros(evt);
        } else {
            if (cbxCriterio.getSelectedIndex() > 1) {
                Validacion.ValidarLetrasEspacio(evt);
                Validacion.cambiarMayusculas(evt);
            }
        }
    
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void CargarTabla() {//metodo q permite cargar a la tabla la lista de creditos activos
        this.modeloTablaFacturas.setLista(this.sFactura.listar());//el modelo recive la lista
        this.tblFacturas.setModel(this.modeloTablaFacturas);//aplica el modelo
        this.tblFacturas.updateUI();//asigna los objetos a la tabla
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Facturas dialog = new Frm_Facturas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxCriterio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
